### ISSUE TITLE
How to find the first zero.

### ISSUE THREAD

**Issue by jumpnbrownweasel** [tower120/hi_sparse_bitset#37]
Hello. Thanks for your work on this!

I didn't see a way in the API to find the first unused slot, i.e., zero bit. Am I just missing it, or do you have a recommendation for doing this efficiently with the current API?

**Comment by jumpnbrownweasel** [comment]
This was a mistake, sorry to pollute your issue list.

**Comment by tower120** [comment]
First unused slot should be previous to first non-empty slot(DataBlock). And the first non-empty slot is the very first DataBlock returned by iterator.
But the thing it - it will be "virtual". You just get it's index range.
Why do you need it?

I think it is possible to make iterator over empty RANGES. Is that what you looked for?
